apiVersion: v1
kind: Service
metadata:
  name: wikijs-svc
spec:
  type: NodePort
  selector:
    app: wikijs
  ports:
  - protocol: TCP
    name: tcp
    port: 3000
    targetPort: 3000
    nodePort: 30030
